### PR TITLE
[wip] Fix: Delete requests need headers to be included in Batch

### PR DESCRIPTION
**Pull request by ChengQian1007**
Delete requests need headers to be included in Batch

Ref to Issue: #65

### CODE REVIEW

**Comment by filak-sap** [comment]
@ChengQian1007 Thank you for taking the time to analyze the problem and post the patch. Do you think you can add/update a test case for this change?

**Comment by filak-sap** [comment]
@ChengQian1007 Thank you for taking the time to analyze the problem and post the patch. Do you think you can add/update a test case for this change?

**Comment by filak-sap** [comment]
@ChengQian1007  I am sorry but I cannot find any reference for your statement. Which OData service implementation do you use?

**Comment by filak-sap** [comment]
D'oh, I've just noticed your issue #65. Well, I am not sure if every Batch request must send some Headers and if it's a good idea to add a random dummy headers just to work around a weak implementation of Batch request generator.

What about to either return and empty dict or better detect None in the function encode_multipart?

**Comment by ChengQian1007** [comment]
@filak-sap I use CDS View generated OData Service.
Thanks for the advices, I will find out whether a normal Delete Request contains header.

**Comment by phanak-sap** [comment]
Closing because this is forgotten PR.. and most probably wrong (does not take into account possibility of Batch requests for data in ATOM format)

**Pull request closed without merging**
