### PR TITLE
Fix parser failing when policies set to nonfatal and annotation being…

### LINKED ISSUE #67: Custom config does not allow bypassing of erroneous service metadata
Hi,
I'm running off commit d218e80ed7cf5933d5391cee74eeef705b513bf1 (sourced from GitHub repo, not PyPI; on 13 Oct 2019).

My SAP service metadata appears to have errors, and I want to bypass the erroneous service metadata (I don't use those erroneous parts).

I understand that the objective of having custom config is to allow us to get around erroneous service metadata which we do not control. To achieve this purpose, is it possible to not have the system dump, but to still return the Client object?

Below is an excerpt of the error, with full source and output in attached Word document.

[GitHub Issue - Custom config does not allow bypassing of erroneous service metadata.docx](https://github.com/SAP/python-pyodata/files/3721651/GitHub.Issue.-.Custom.config.does.not.allow.bypassing.of.erroneous.service.metadata.docx)

WARNING: Ignoring qualified Annotations of RE_CN_CONTRACT_ODATA.VL_SH_REMMMNC/RESPONSIBLE
WARNING: Ignoring qualified Annotations of RE_CN_CONTRACT_ODATA.VL_SH_REMMMNC/RESPONSIBLE
WARNING: Ignoring qualified Annotations of RE_CN_CONTRACT_ODATA.VL_SH_REMMMNC/RESPONSIBLE

KeyError                                  Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\pyodata\v2\model.py in proprty(self, value)
   2101                 try:
-> 2102                     param.local_property = etype.proprty(param.local_property_name)
   2103                 except KeyError:

C:\ProgramData\Anaconda3\lib\site-packages\pyodata\v2\model.py in proprty(self, property_name)
   1193     def proprty(self, property_name):
-> 1194         return self._properties[property_name]
   1195 

KeyError: 'Recntype'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-47-7d19419f1c10> in <module>
     20 )
     21 
---> 22 service = pyodata.Client(SERVICE_URL, session, config=custom_config)

C:\ProgramData\Anaconda3\lib\site-packages\pyodata\client.py in __new__(cls, url, connection, odata_version, namespaces, config)
     57             # create model instance from received metadata
     58             logger.info('Creating OData Schema (version: %d)', odata_version)
---> 59             schema = pyodata.v2.model.MetadataBuilder(resp.content, config=config).build()
     60 
     61             # create service instance based on model we have

C:\ProgramData\Anaconda3\lib\site-packages\pyodata\v2\model.py in build(self)
   2458 
   2459         edm_schemas = xml.xpath('/edmx:Edmx/edmx:DataServices/edm:Schema', namespaces=self._config.namespaces)
-> 2460         schema = Schema.from_etree(edm_schemas, self._config)
   2461         return schema
   2462 

C:\ProgramData\Anaconda3\lib\site-packages\pyodata\v2\model.py in from_etree(schema_nodes, config)
   1168                         config.err_policy(ParserError.ANNOTATION).resolve(ex)
   1169                     else:
-> 1170                         annotation.proprty = target_proprty
   1171                         target_proprty.value_helper = annotation
   1172 

C:\ProgramData\Anaconda3\lib\site-packages\pyodata\v2\model.py in proprty(self, value)
   2103                 except KeyError:
   2104                     raise RuntimeError('{0} of {1} points to an non existing LocalDataProperty {2} of {3}'.format(
-> 2105                         param, self, param.local_property_name, etype))
   2106 
   2107     @property

RuntimeError: ValueHelperParameter(Recntype) of ValueHelper(ContractObjectData/Objid_IS) points to an non existing LocalDataProperty Recntype of EntityType(ContractObjectData)

### PR DESCRIPTION
**Pull request by mamiksik**
… correctly parsed but it's properties pointing to unknown entities

Resolves #67

### CODE REVIEW

**Comment by amosang** [comment]
Hi,
I've helped to test the fix manually by doing the following:
image
- pip install directly from GitHub repo.

image
- Pulled code from PR branch.
- Manually copied model.py to C:\ProgramData\Anaconda3\Lib\site-packages\pyodata\v2
- Ref: https://help.github.com/en/articles/checking-out-pull-requests-locally

image
- Python source code.

image
- Same error as before. Implies that the fix did not work?

**Comment by mamiksik** [comment]
I will have another look at it. Sorry for the confusion. I tested it on the provided metadata and it worked on my machine.

**Comment by filak-sap** [comment]
@mamiksik - The referrenced issue contains the problematic $metadata. Download it, hook it in the tests, fix the problem, copy the problematic $metadata part to our standard $metadata or create a fresh new test case.

**Comment by mamiksik** [comment]
@filak-sap I added the tests. @amosang Please have look at the `test_missing_property_referenced_in_annotation`, it is simulating the issues raised by your metadata and it behaves accordingly. I also again tried your original metadata and I still have no problem parsing them when the annotation policy is set to ignore or warning.

**Comment by filak-sap** [comment]
@mamiksik  Good job! Meanwhile, I've updated CONTRIBUTING guidelines and I would like to ask you to update CHANGELOG.md.

https://github.com/SAP/python-pyodata/blob/master/CONTRIBUTING.md

**Comment by filak-sap** [comment]
@amosang You need to use `ParserError.ANNOTATION = PolicyIgnore()`. We should enrich error reports with the hints how to suppress them.

**Comment by amosang** [comment]
I did this "pip install git+https://github.com/SAP/python-pyodata.git@refs/pull/68/merge". This should merge in the PR#68.

Unfortunately our SAP system has just been patched with SAP Note 2850479 which fixed the erroneous metadata, so I no longer have the problem metadata to test with. 

I tried to run test_missing_property_referenced_in_annotation(mock_warning, xml_builder_factory), and copied any required references from tests/conftest.py, but am not sure how to call test_missing_property_referenced_in_annotation(), in particular what to supply for xml_builder_factory parameter. Will be glad to test this manually if you could provide some tips please.

**Pull request closed without merging**
