### PR TITLE
inlinecount support and ProgramError with fixed tests

### PR DESCRIPTION
**Pull request by s7oev**
Add support for inlinecount and a ProgramError exception as discussed in #120 

Fixed test issues as discussed [in this comment](
https://github.com/SAP/python-pyodata/pull/121#issuecomment-669817083).

### CODE REVIEW

**Comment by filak-sap** [comment]
@s7oev Is this PR ready to be reviewed?

**Comment by filak-sap** [comment]
@s7oev  I would like to ask you to updated CHANGELONG.md and add a paragraph about the feature to https://github.com/SAP/python-pyodata/blob/master/docs/usage/querying.rst#get-a-count-of-entities

**Comment by s7oev** [comment]
@filak-sap yes, the PR is ready to be reviewed, sorry, did not realize I have to explicitly mention it.

I will update the changelog and the docs. For the changelog, should I put it in the 1.6.0 version, 'Added' section?

**Comment by s7oev** [comment]
@filak-sap I've currently added the changelog and the updated docs to a [separate branch in my repo](https://github.com/s7oev/python-pyodata/tree/docu).

**Comment by filak-sap** [comment]
Thank you very much for you contribution. I have rebased your branch to the current master and pushed the following commits:
- 3b680b3 errors: create ProgramError
- bf8a1a9 service: add support for inlinecount
- 5504779 documentation and changelog for inlinecount

**Pull request closed without merging**
