### PR TITLE
Django style filtering for GetEntitySetRequest

### PR DESCRIPTION
**Pull request by bartonip**
The existing filtering mechanism is not very intuitive, requiring interpolation of OData queries or using the convoluted boolean logic syntax of `GetEntitySetFilter` to achieve complex queries. 

I have implemented a Django-like filtering system that allows filtering of EntitySets in a much more intuitive way.

**Syntax**
---
For example, a simple equivalency query was previously written like this:
```
request = service.entity_sets.Employees.get_entities().filter("FirstName eq 'Tim' and LastName eq 'Smith'")
```

or even more confusingly: 
```
request = service.entity_sets.Employees.get_entities().filter(sef.and_(
                                                             request.FirstName == 'Tim',
                                                             request.LastName == 'Smith'))
```

With this proposed update, future calls will look like this.

```
request = service.entity_sets.Employees.get_entities().filter(FirstName="Tim", LastName="Smith")
```

Tell me that's not way more beautiful. ;)

**Filter Expressions**
---

Next, I have implemented some lookups using Django-like syntax that opens up some more advanced query scenarios.
The operators `lt`, `lte`, `gt`, `gte`, `in`, `contains`, `startswith`, `endswith`, `length` and `range` have been implemented.

Examples below:
```
request = service.entity_sets.Employees.get_entities().filter(ID__lte=20)

request = service.entity_sets.Employees.get_entities().filter(ID__gt=20)

request = service.entity_sets.Employees.get_entities().filter(ID__in=[20, 21, 22])

request = service.entity_sets.Employees.get_entities().filter(FirstName__contains="Tim")

request = service.entity_sets.Employees.get_entities().filter(FirstName__length=3)

```

There is also the introduction of the `FilterExpression` class which is equivalent to Django's Q class.

This allows common queries to be stored as objects:
```
from pyodata.v2.service import FilterExpression as Q
company = Q(CompanyID=1234)

request = service.entity_sets.Employees.get_entities().filter(company, FirstName="Tim", LastName__startswith="S")

```

This also allows the `or` operator to be used to or statements:
```
request = service.entity_sets.Employees.get_entities().filter(Q(FirstName="Tim") | Q(FirstName="John"), LastName="Smith))
```

All changes are backwards compatible and do not disrupt existing implementations of this library, and upgrading to this syntax should be simple if not trivial.

### CODE REVIEW

**Comment by filak-sap** [comment]
I am not sure what a linter you use but neither pylint nor flake8 are configured to enforce use of double quotes.

In general, please avoid code style changes - my ideology: what was once accepted to master should stay formatted as it is unless there are other reason for touching it (code style changes makes reviews almost impossible).

**Comment by bartonip** [comment]
Apologies, VSCode was pointed to the wrong env and had our internal linting rules applied.

This has been rectified.

**Comment by filak-sap** [comment]
Would you mind if I push the version after applying the patch https://github.com/filak-sap/python-pyodata-1/commit/548c12e5c0b14bbc13dc7ff8b4239cb5945feaaa ?

**Comment by filak-sap** [comment]
You can see the version after my changes at: https://github.com/SAP/python-pyodata/compare/master...filak-sap:django_style_filter_review

**Comment by bartonip** [comment]
Looks good to me!

**Pull request closed without merging**
